# ui_final_design_v3_2.py
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_design_v3_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1692, 975)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color: grey\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        self.label_title.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("QLabel{\n"
"color: white\n"
"}")
        self.label_title.setText("")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_3.addWidget(self.label_title)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Layout_inputs = QtWidgets.QGridLayout()
        self.Layout_inputs.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.Layout_inputs.setVerticalSpacing(12)
        self.Layout_inputs.setObjectName("Layout_inputs")
        self.saglikli_kontrol_color_box = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saglikli_kontrol_color_box.sizePolicy().hasHeightForWidth())
        self.saglikli_kontrol_color_box.setSizePolicy(sizePolicy)
        self.saglikli_kontrol_color_box.setMinimumSize(QtCore.QSize(20, 20))
        self.saglikli_kontrol_color_box.setMaximumSize(QtCore.QSize(20, 20))
        self.saglikli_kontrol_color_box.setStyleSheet("QFrame{\n"
"background-color: #87CEEB ; /* İstediğiniz renk kodunu buraya yazın */\n"
"border: 2px solid #333333; /* Kenar çerçevesini ayarlamak için opsiyonel */\n"
"border-radius: 5px; /* Köşeleri yuvarlamak için opsiyonel */\n"
"border-color: white\n"
"}")
        self.saglikli_kontrol_color_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saglikli_kontrol_color_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saglikli_kontrol_color_box.setObjectName("saglikli_kontrol_color_box")
        self.Layout_inputs.addWidget(self.saglikli_kontrol_color_box, 2, 5, 1, 1)
        self.label_esittir = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_esittir.sizePolicy().hasHeightForWidth())
        self.label_esittir.setSizePolicy(sizePolicy)
        self.label_esittir.setMinimumSize(QtCore.QSize(20, 20))
        self.label_esittir.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_esittir.setFont(font)
        self.label_esittir.setStyleSheet("background-color: transparent;\n"
"color: White")
        self.label_esittir.setObjectName("label_esittir")
        self.Layout_inputs.addWidget(self.label_esittir, 4, 1, 1, 1)
        self.label_belirsiz = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_belirsiz.sizePolicy().hasHeightForWidth())
        self.label_belirsiz.setSizePolicy(sizePolicy)
        self.label_belirsiz.setMinimumSize(QtCore.QSize(150, 25))
        self.label_belirsiz.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_belirsiz.setFont(font)
        self.label_belirsiz.setStyleSheet("background-color: transparent;\n"
"color: White")
        self.label_belirsiz.setObjectName("label_belirsiz")
        self.Layout_inputs.addWidget(self.label_belirsiz, 3, 0, 1, 1)
        self.label_tasiyici = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tasiyici.sizePolicy().hasHeightForWidth())
        self.label_tasiyici.setSizePolicy(sizePolicy)
        self.label_tasiyici.setMinimumSize(QtCore.QSize(150, 25))
        self.label_tasiyici.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_tasiyici.setFont(font)
        self.label_tasiyici.setStyleSheet("QLabel{\n"
"background-color: transparent;\n"
"color: White}")
        self.label_tasiyici.setObjectName("label_tasiyici")
        self.Layout_inputs.addWidget(self.label_tasiyici, 2, 0, 1, 1)
        self.label_saglikli_kontrol = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_saglikli_kontrol.sizePolicy().hasHeightForWidth())
        self.label_saglikli_kontrol.setSizePolicy(sizePolicy)
        self.label_saglikli_kontrol.setMinimumSize(QtCore.QSize(150, 25))
        self.label_saglikli_kontrol.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_saglikli_kontrol.setFont(font)
        self.label_saglikli_kontrol.setStyleSheet("background-color: transparent;\n"
"color: White")
        self.label_saglikli_kontrol.setObjectName("label_saglikli_kontrol")
        self.Layout_inputs.addWidget(self.label_saglikli_kontrol, 2, 3, 1, 1)
        self.doubleSpinBox_tasiyici = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_tasiyici.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_tasiyici.setSizePolicy(sizePolicy)
        self.doubleSpinBox_tasiyici.setMinimumSize(QtCore.QSize(70, 20))
        self.doubleSpinBox_tasiyici.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_tasiyici.setFont(font)
        self.doubleSpinBox_tasiyici.setStyleSheet("QDoubleSpinBox{\n"
"background: #D3D3D3;\n"
"color: black;              /* Siyah metin rengi */\n"
"border: dashed #FFFFFF; /* Beyaz kesikli çizgi */\n"
"border-radius: 5px;        /* Köşeleri yuvarla */\n"
"}")
        self.doubleSpinBox_tasiyici.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_tasiyici.setDecimals(4)
        self.doubleSpinBox_tasiyici.setMinimum(0.1)
        self.doubleSpinBox_tasiyici.setMaximum(0.65)
        self.doubleSpinBox_tasiyici.setSingleStep(0.01)
        self.doubleSpinBox_tasiyici.setProperty("value", 0.5499)
        self.doubleSpinBox_tasiyici.setObjectName("doubleSpinBox_tasiyici")
        self.Layout_inputs.addWidget(self.doubleSpinBox_tasiyici, 2, 2, 1, 1)
        self.checkBox_istatistik = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_istatistik.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_istatistik.sizePolicy().hasHeightForWidth())
        self.checkBox_istatistik.setSizePolicy(sizePolicy)
        self.checkBox_istatistik.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBox_istatistik.setMaximumSize(QtCore.QSize(510, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_istatistik.setFont(font)
        self.checkBox_istatistik.setStyleSheet("background-color: transparent;\n"
"color: White")
        self.checkBox_istatistik.setChecked(True)
        self.checkBox_istatistik.setObjectName("checkBox_istatistik")
        self.Layout_inputs.addWidget(self.checkBox_istatistik, 5, 0, 1, 5)
        self.label_tasiyici_kontrol = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tasiyici_kontrol.sizePolicy().hasHeightForWidth())
        self.label_tasiyici_kontrol.setSizePolicy(sizePolicy)
        self.label_tasiyici_kontrol.setMinimumSize(QtCore.QSize(150, 25))
        self.label_tasiyici_kontrol.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_tasiyici_kontrol.setFont(font)
        self.label_tasiyici_kontrol.setStyleSheet("QLabel{\n"
"background-color: transparent;\n"
"color: White}")
        self.label_tasiyici_kontrol.setObjectName("label_tasiyici_kontrol")
        self.Layout_inputs.addWidget(self.label_tasiyici_kontrol, 3, 3, 1, 1)
        self.lineEdit_standart_kuyu = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_standart_kuyu.sizePolicy().hasHeightForWidth())
        self.lineEdit_standart_kuyu.setSizePolicy(sizePolicy)
        self.lineEdit_standart_kuyu.setMinimumSize(QtCore.QSize(70, 20))
        self.lineEdit_standart_kuyu.setMaximumSize(QtCore.QSize(45, 20))
        self.lineEdit_standart_kuyu.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_standart_kuyu.setFont(font)
        self.lineEdit_standart_kuyu.setStyleSheet("QLineEdit{\n"
"background: #D3D3D3;       /* Açık gri arka plan */\n"
"color: black;              /* Siyah metin rengi */\n"
"border: dashed #FFFFFF; /* Beyaz kesikli çizgi */\n"
"border-radius: 5px;        /* Köşeleri yuvarla */\n"
"}")
        self.lineEdit_standart_kuyu.setText("")
        self.lineEdit_standart_kuyu.setMaxLength(3)
        self.lineEdit_standart_kuyu.setCursorPosition(0)
        self.lineEdit_standart_kuyu.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_standart_kuyu.setObjectName("lineEdit_standart_kuyu")
        self.Layout_inputs.addWidget(self.lineEdit_standart_kuyu, 4, 2, 1, 1)
        self.logo_container = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_container.sizePolicy().hasHeightForWidth())
        self.logo_container.setSizePolicy(sizePolicy)
        self.logo_container.setMinimumSize(QtCore.QSize(510, 100))
        self.logo_container.setMaximumSize(QtCore.QSize(510, 100))
        self.logo_container.setStyleSheet("QLabel{\n"
"background-color:transparent}")
        self.logo_container.setText("")
        self.logo_container.setPixmap(QtGui.QPixmap("../../sma_gui_v7_last/pharmalinelogo.svg"))
        self.logo_container.setScaledContents(True)
        self.logo_container.setObjectName("logo_container")
        self.Layout_inputs.addWidget(self.logo_container, 0, 0, 1, 6)
        self.tasiyici_kontrol_color_box = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tasiyici_kontrol_color_box.sizePolicy().hasHeightForWidth())
        self.tasiyici_kontrol_color_box.setSizePolicy(sizePolicy)
        self.tasiyici_kontrol_color_box.setMinimumSize(QtCore.QSize(20, 20))
        self.tasiyici_kontrol_color_box.setMaximumSize(QtCore.QSize(20, 20))
        self.tasiyici_kontrol_color_box.setStyleSheet("QFrame{\n"
"background-color: #87CEEB ; /* İstediğiniz renk kodunu buraya yazın */\n"
"border: 2px solid #333333; /* Kenar çerçevesini ayarlamak için opsiyonel */\n"
"border-radius: 5px; /* Köşeleri yuvarlamak için opsiyonel */\n"
"border-color: white\n"
"}")
        self.tasiyici_kontrol_color_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tasiyici_kontrol_color_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tasiyici_kontrol_color_box.setObjectName("tasiyici_kontrol_color_box")
        self.Layout_inputs.addWidget(self.tasiyici_kontrol_color_box, 3, 5, 1, 1)
        self.line_edit_saglikli_kontrol = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_saglikli_kontrol.setMinimumSize(QtCore.QSize(70, 20))
        self.line_edit_saglikli_kontrol.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit_saglikli_kontrol.setFont(font)
        self.line_edit_saglikli_kontrol.setStyleSheet("background: #D3D3D3;       /* Açık gri arka plan */\n"
"color: black;              /* Siyah metin rengi */\n"
"border: dashed #FFFFFF; /* Beyaz kesikli çizgi */\n"
"border-radius: 5px;        /* Köşeleri yuvarla */\n"
"")
        self.line_edit_saglikli_kontrol.setMaxLength(3)
        self.line_edit_saglikli_kontrol.setAlignment(QtCore.Qt.AlignCenter)
        self.line_edit_saglikli_kontrol.setObjectName("line_edit_saglikli_kontrol")
        self.Layout_inputs.addWidget(self.line_edit_saglikli_kontrol, 2, 4, 1, 1)
        self.label_kucuk_esittir_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_kucuk_esittir_2.sizePolicy().hasHeightForWidth())
        self.label_kucuk_esittir_2.setSizePolicy(sizePolicy)
        self.label_kucuk_esittir_2.setMinimumSize(QtCore.QSize(20, 20))
        self.label_kucuk_esittir_2.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_kucuk_esittir_2.setFont(font)
        self.label_kucuk_esittir_2.setStyleSheet("background-color: transparent;\n"
"color: White")
        self.label_kucuk_esittir_2.setObjectName("label_kucuk_esittir_2")
        self.Layout_inputs.addWidget(self.label_kucuk_esittir_2, 3, 1, 1, 1)
        self.label_ntc_kontrol = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ntc_kontrol.sizePolicy().hasHeightForWidth())
        self.label_ntc_kontrol.setSizePolicy(sizePolicy)
        self.label_ntc_kontrol.setMinimumSize(QtCore.QSize(150, 25))
        self.label_ntc_kontrol.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ntc_kontrol.setFont(font)
        self.label_ntc_kontrol.setStyleSheet("background-color: transparent;\n"
"color: White")
        self.label_ntc_kontrol.setObjectName("label_ntc_kontrol")
        self.Layout_inputs.addWidget(self.label_ntc_kontrol, 4, 3, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_3.setSpacing(12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_temizle = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_temizle.sizePolicy().hasHeightForWidth())
        self.pushButton_temizle.setSizePolicy(sizePolicy)
        self.pushButton_temizle.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_temizle.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_temizle.setFont(font)
        self.pushButton_temizle.setStyleSheet("QPushButton {\n"
"    background-color: #4ca1af;       /* Varsayılan mavi arka plan */\n"
"    color: white;                    /* Yazı rengi: Beyaz */\n"
"    border: 2px solid #FFFFFF;       /* Beyaz çerçeve */\n"
"    border-radius: 10px;             /* Yuvarlak köşeler */\n"
"    text-align: center;              /* Metni ortala */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #76c7d0;       /* Hover: Daha açık mavi */\n"
"    border-color: #d9f1f5;           /* Çerçeve: Daha açık beyaz-mavi ton */\n"
"    color: white;                    /* Yazı rengi: Beyaz */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2a7881;       /* Basıldığında: Daha koyu mavi-yeşil ton */\n"
"    border-color: #6fb4ba;           /* Çerçeve: Soluk mavi */\n"
"    color: #e6f7f8;                  /* Yazı: Hafif açık beyaz */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #d3d3d3;       /* Devre dışı: Gri arka plan */\n"
"    color: #a8a8a8;                  /* Yazı: Daha koyu gri */\n"
"    border-color: #c0c0c0;           /* Çerçeve: Orta gri */\n"
"}\n"
"")
        self.pushButton_temizle.setObjectName("pushButton_temizle")
        self.gridLayout_3.addWidget(self.pushButton_temizle, 0, 1, 1, 1)
        self.pushButton_analiz_et = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_analiz_et.sizePolicy().hasHeightForWidth())
        self.pushButton_analiz_et.setSizePolicy(sizePolicy)
        self.pushButton_analiz_et.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_analiz_et.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_analiz_et.setFont(font)
        self.pushButton_analiz_et.setStyleSheet("QPushButton {\n"
"    background-color: #4ca1af;       /* Varsayılan mavi arka plan */\n"
"    color: white;                    /* Yazı rengi: Beyaz */\n"
"    border: 2px solid #FFFFFF;       /* Beyaz çerçeve */\n"
"    border-radius: 10px;             /* Yuvarlak köşeler */\n"
"    text-align: center;              /* Metni ortala */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #76c7d0;       /* Hover: Daha açık mavi */\n"
"    border-color: #d9f1f5;           /* Çerçeve: Daha açık beyaz-mavi ton */\n"
"    color: white;                    /* Yazı rengi: Beyaz */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2a7881;       /* Basıldığında: Daha koyu mavi-yeşil ton */\n"
"    border-color: #6fb4ba;           /* Çerçeve: Soluk mavi */\n"
"    color: #e6f7f8;                  /* Yazı: Hafif açık beyaz */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #d3d3d3;       /* Devre dışı: Gri arka plan */\n"
"    color: #a8a8a8;                  /* Yazı: Daha koyu gri */\n"
"    border-color: #c0c0c0;           /* Çerçeve: Orta gri */\n"
"}\n"
"")
        self.pushButton_analiz_et.setObjectName("pushButton_analiz_et")
        self.gridLayout_3.addWidget(self.pushButton_analiz_et, 0, 0, 1, 1)
        self.pushButton_disaaktar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_disaaktar.sizePolicy().hasHeightForWidth())
        self.pushButton_disaaktar.setSizePolicy(sizePolicy)
        self.pushButton_disaaktar.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_disaaktar.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_disaaktar.setFont(font)
        self.pushButton_disaaktar.setStyleSheet("QPushButton {\n"
"    background-color: #4ca1af;       /* Varsayılan mavi arka plan */\n"
"    color: white;                    /* Yazı rengi: Beyaz */\n"
"    border: 2px solid #FFFFFF;       /* Beyaz çerçeve */\n"
"    border-radius: 10px;             /* Yuvarlak köşeler */\n"
"    text-align: center;              /* Metni ortala */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #76c7d0;       /* Hover: Daha açık mavi */\n"
"    border-color: #d9f1f5;           /* Çerçeve: Daha açık beyaz-mavi ton */\n"
"    color: white;                    /* Yazı rengi: Beyaz */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2a7881;       /* Basıldığında: Daha koyu mavi-yeşil ton */\n"
"    border-color: #6fb4ba;           /* Çerçeve: Soluk mavi */\n"
"    color: #e6f7f8;                  /* Yazı: Hafif açık beyaz */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #d3d3d3;       /* Devre dışı: Gri arka plan */\n"
"    color: #a8a8a8;                  /* Yazı: Daha koyu gri */\n"
"    border-color: #c0c0c0;           /* Çerçeve: Orta gri */\n"
"}\n"
"")
        self.pushButton_disaaktar.setObjectName("pushButton_disaaktar")
        self.gridLayout_3.addWidget(self.pushButton_disaaktar, 1, 1, 1, 1)
        self.pushButton_iceaktar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_iceaktar.sizePolicy().hasHeightForWidth())
        self.pushButton_iceaktar.setSizePolicy(sizePolicy)
        self.pushButton_iceaktar.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_iceaktar.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_iceaktar.setFont(font)
        self.pushButton_iceaktar.setStyleSheet("QPushButton {\n"
"    background-color: #4ca1af;       /* Varsayılan mavi arka plan */\n"
"    color: white;                    /* Yazı rengi: Beyaz */\n"
"    border: 2px solid #FFFFFF;       /* Beyaz çerçeve */\n"
"    border-radius: 10px;             /* Yuvarlak köşeler */\n"
"    text-align: center;              /* Metni ortala */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #76c7d0;       /* Hover: Daha açık mavi */\n"
"    border-color: #d9f1f5;           /* Çerçeve: Daha açık beyaz-mavi ton */\n"
"    color: white;                    /* Yazı rengi: Beyaz */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2a7881;       /* Basıldığında: Daha koyu mavi-yeşil ton */\n"
"    border-color: #6fb4ba;           /* Çerçeve: Soluk mavi */\n"
"    color: #e6f7f8;                  /* Yazı: Hafif açık beyaz */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #d3d3d3;       /* Devre dışı: Gri arka plan */\n"
"    color: #a8a8a8;                  /* Yazı: Daha koyu gri */\n"
"    border-color: #c0c0c0;           /* Çerçeve: Orta gri */\n"
"}\n"
"")
        self.pushButton_iceaktar.setObjectName("pushButton_iceaktar")
        self.gridLayout_3.addWidget(self.pushButton_iceaktar, 1, 0, 1, 1)
        self.Layout_inputs.addLayout(self.gridLayout_3, 6, 0, 1, 6)
        self.ntc_kontrol_color_box = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ntc_kontrol_color_box.sizePolicy().hasHeightForWidth())
        self.ntc_kontrol_color_box.setSizePolicy(sizePolicy)
        self.ntc_kontrol_color_box.setMinimumSize(QtCore.QSize(20, 20))
        self.ntc_kontrol_color_box.setMaximumSize(QtCore.QSize(20, 20))
        self.ntc_kontrol_color_box.setStyleSheet("QFrame{\n"
"background-color: #87CEEB ; /* İstediğiniz renk kodunu buraya yazın */\n"
"border: 2px solid #333333; /* Kenar çerçevesini ayarlamak için opsiyonel */\n"
"border-radius: 5px; /* Köşeleri yuvarlamak için opsiyonel */\n"
"border-color: white}")
        self.ntc_kontrol_color_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ntc_kontrol_color_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ntc_kontrol_color_box.setObjectName("ntc_kontrol_color_box")
        self.Layout_inputs.addWidget(self.ntc_kontrol_color_box, 4, 5, 1, 1)
        self.doubleSpinBox_belirsiz = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_belirsiz.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_belirsiz.setSizePolicy(sizePolicy)
        self.doubleSpinBox_belirsiz.setMinimumSize(QtCore.QSize(70, 20))
        self.doubleSpinBox_belirsiz.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_belirsiz.setFont(font)
        self.doubleSpinBox_belirsiz.setStyleSheet("QDoubleSpinBox{\n"
"background: #D3D3D3;\n"
"color: black;              /* Siyah metin rengi */\n"
"border: dashed #FFFFFF; /* Beyaz kesikli çizgi */\n"
"border-radius: 5px;        /* Köşeleri yuvarla */\n"
"}")
        self.doubleSpinBox_belirsiz.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_belirsiz.setDecimals(4)
        self.doubleSpinBox_belirsiz.setMinimum(0.45)
        self.doubleSpinBox_belirsiz.setMaximum(1.2)
        self.doubleSpinBox_belirsiz.setSingleStep(0.01)
        self.doubleSpinBox_belirsiz.setProperty("value", 0.5999)
        self.doubleSpinBox_belirsiz.setObjectName("doubleSpinBox_belirsiz")
        self.Layout_inputs.addWidget(self.doubleSpinBox_belirsiz, 3, 2, 1, 1)
        self.label_kucuk_esittir_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_kucuk_esittir_1.sizePolicy().hasHeightForWidth())
        self.label_kucuk_esittir_1.setSizePolicy(sizePolicy)
        self.label_kucuk_esittir_1.setMinimumSize(QtCore.QSize(20, 20))
        self.label_kucuk_esittir_1.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_kucuk_esittir_1.setFont(font)
        self.label_kucuk_esittir_1.setStyleSheet("background-color: transparent;\n"
"color: White")
        self.label_kucuk_esittir_1.setObjectName("label_kucuk_esittir_1")
        self.Layout_inputs.addWidget(self.label_kucuk_esittir_1, 2, 1, 1, 1)
        self.line_edit_NTC_kontrol = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_NTC_kontrol.setMinimumSize(QtCore.QSize(70, 20))
        self.line_edit_NTC_kontrol.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit_NTC_kontrol.setFont(font)
        self.line_edit_NTC_kontrol.setStyleSheet("background: #D3D3D3;       /* Açık gri arka plan */\n"
"color: black;              /* Siyah metin rengi */\n"
"border: dashed #FFFFFF; /* Beyaz kesikli çizgi */\n"
"border-radius: 5px;        /* Köşeleri yuvarla */\n"
"")
        self.line_edit_NTC_kontrol.setMaxLength(3)
        self.line_edit_NTC_kontrol.setAlignment(QtCore.Qt.AlignCenter)
        self.line_edit_NTC_kontrol.setObjectName("line_edit_NTC_kontrol")
        self.Layout_inputs.addWidget(self.line_edit_NTC_kontrol, 4, 4, 1, 1)
        self.label_standart_kuyu = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_standart_kuyu.sizePolicy().hasHeightForWidth())
        self.label_standart_kuyu.setSizePolicy(sizePolicy)
        self.label_standart_kuyu.setMinimumSize(QtCore.QSize(150, 25))
        self.label_standart_kuyu.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_standart_kuyu.setFont(font)
        self.label_standart_kuyu.setStyleSheet("background-color: transparent;\n"
"color: White")
        self.label_standart_kuyu.setObjectName("label_standart_kuyu")
        self.Layout_inputs.addWidget(self.label_standart_kuyu, 4, 0, 1, 1)
        self.line_edit_tasiyici_kontrol = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_tasiyici_kontrol.setMinimumSize(QtCore.QSize(70, 20))
        self.line_edit_tasiyici_kontrol.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit_tasiyici_kontrol.setFont(font)
        self.line_edit_tasiyici_kontrol.setStyleSheet("QLineEdit{\n"
"background: #D3D3D3;       /* Açık gri arka plan */\n"
"color: black;              /* Siyah metin rengi */\n"
"border: dashed #FFFFFF; /* Beyaz kesikli çizgi */\n"
"border-radius: 5px;        /* Köşeleri yuvarla */\n"
"}")
        self.line_edit_tasiyici_kontrol.setMaxLength(3)
        self.line_edit_tasiyici_kontrol.setAlignment(QtCore.Qt.AlignCenter)
        self.line_edit_tasiyici_kontrol.setObjectName("line_edit_tasiyici_kontrol")
        self.Layout_inputs.addWidget(self.line_edit_tasiyici_kontrol, 3, 4, 1, 1)
        self.label_drag_drop_area = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_drag_drop_area.sizePolicy().hasHeightForWidth())
        self.label_drag_drop_area.setSizePolicy(sizePolicy)
        self.label_drag_drop_area.setMinimumSize(QtCore.QSize(510, 90))
        self.label_drag_drop_area.setMaximumSize(QtCore.QSize(510, 90))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_drag_drop_area.setFont(font)
        self.label_drag_drop_area.setAcceptDrops(True)
        self.label_drag_drop_area.setStyleSheet("QLabel{\n"
"border: 2px dashed #FFFFFF; /* border: dashed  Kesikli çizgi ve siyah renk */\n"
"border-radius: 15px;         /* Köşeleri yuvarlatmak için opsiyonel */ \n"
"background: #a6a6a6;\n"
"color: white\n"
"\n"
"}")
        self.label_drag_drop_area.setAlignment(QtCore.Qt.AlignCenter)
        self.label_drag_drop_area.setObjectName("label_drag_drop_area")
        self.Layout_inputs.addWidget(self.label_drag_drop_area, 1, 0, 1, 6)
        self.horizontalLayout.addLayout(self.Layout_inputs)
        self.regration_container = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regration_container.sizePolicy().hasHeightForWidth())
        self.regration_container.setSizePolicy(sizePolicy)
        self.regration_container.setMinimumSize(QtCore.QSize(0, 450))
        self.regration_container.setMaximumSize(QtCore.QSize(16777215, 450))
        self.regration_container.setStyleSheet("QWidget{\n"
"background: #a6a6a6;\n"
"padding: 0px;\n"
"margin: 0px;\n"
"border: 2px solid transparent;\n"
"border-radius: 15px;\n"
"\n"
"}")
        self.regration_container.setObjectName("regration_container")
        self.horizontalLayout.addWidget(self.regration_container)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.table_widget_resulttable = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_widget_resulttable.sizePolicy().hasHeightForWidth())
        self.table_widget_resulttable.setSizePolicy(sizePolicy)
        self.table_widget_resulttable.setMinimumSize(QtCore.QSize(600, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.table_widget_resulttable.setFont(font)
        self.table_widget_resulttable.setAutoFillBackground(False)
        self.table_widget_resulttable.setStyleSheet("/* Genel tablo arka planı */\n"
"QTableWidget {\n"
"    background-color: #f9f9f9; /* Hafif gri bir arka plan */\n"
"    border: 1px solid #d6d6d6; /* İnce bir kenarlık */\n"
"    gridline-color: #e1e1e1; /* Hücre ızgara çizgi rengi */\n"
"    color: #333333; /* Yazı rengi */\n"
"}\n"
"\n"
"/* Başlık stili */\n"
"QHeaderView::section {\n"
"    background-color: #4ca1af; /* Koyu gri bir arka plan */\n"
"    color: white; /* Beyaz yazı */\n"
"    font-family: \"Arial\";\n"
"    font-size: 16px;\n"
"    font-weight: bold; /* Yazı tipi: Kalın */\n"
"    padding: 3px 0px 3px 0px;\n"
"    border: 1px solid #d6d6d6; /* İnce kenarlık */\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Satırların alternatif arka plan renkleri */\n"
"QTableWidget::item {\n"
"    selection-background-color: #90CAF9; /* Seçim sırasında mavi arka plan */\n"
"    selection-color: white; /* Seçili hücrede beyaz yazı rengi */\n"
"}\n"
"\n"
"QTableWidget::item:nth-child(even) {\n"
"    background-color: #f2f2f2; /* Çift satırlar için açık gri arka plan */\n"
"}\n"
"QTableWidget::item:nth-child(odd) {\n"
"    background-color: #ffffff; /* Tek satırlar için beyaz arka plan */\n"
"}\n"
"\n"
"/* Kenarlıklar ve odak efekti */\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #4CAF50; /* Sol üst köşe */\n"
"    border: 1px solid #d6d6d6;\n"
"}\n"
"\n"
"QTableWidget:focus {\n"
"    border: 2px solid #4CAF50; /* Odaklandığında yeşil kenarlık */\n"
"}\n"
"\n"
"/* Scrollbar stili */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f0f0f0;\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #c1c1c1;\n"
"    min-height: 20px;\n"
"}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Hover efektleri */\n"
"QTableWidget::item:hover {\n"
"    background-color: #e8f5e9; /* Hafif yeşil bir hover efekti */\n"
"    color: #333333;\n"
"}\n"
"")
        self.table_widget_resulttable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_widget_resulttable.setRowCount(96)
        self.table_widget_resulttable.setObjectName("table_widget_resulttable")
        self.table_widget_resulttable.setColumnCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_resulttable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_resulttable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_resulttable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_resulttable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_resulttable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_resulttable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_resulttable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_resulttable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_resulttable.setHorizontalHeaderItem(8, item)
        self.table_widget_resulttable.horizontalHeader().setCascadingSectionResizes(True)
        self.table_widget_resulttable.horizontalHeader().setMinimumSectionSize(44)
        self.table_widget_resulttable.horizontalHeader().setStretchLastSection(False)
        self.table_widget_resulttable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_widget_resulttable)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PCR_graph_container = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PCR_graph_container.sizePolicy().hasHeightForWidth())
        self.PCR_graph_container.setSizePolicy(sizePolicy)
        self.PCR_graph_container.setMinimumSize(QtCore.QSize(0, 450))
        self.PCR_graph_container.setMaximumSize(QtCore.QSize(16777215, 450))
        self.PCR_graph_container.setStyleSheet("QWidget{\n"
"background:  #a6a6a6;\n"
"padding: 0px;\n"
"margin: 0px;\n"
"border: 2px solid transparent;\n"
"border-radius: 15px;\n"
"\n"
"}")
        self.PCR_graph_container.setObjectName("PCR_graph_container")
        self.verticalLayout_2.addWidget(self.PCR_graph_container)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.checkBox_FAM = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_FAM.sizePolicy().hasHeightForWidth())
        self.checkBox_FAM.setSizePolicy(sizePolicy)
        self.checkBox_FAM.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBox_FAM.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox_FAM.setStyleSheet("background-color: transparent;\n"
"color: White")
        self.checkBox_FAM.setObjectName("checkBox_FAM")
        self.horizontalLayout_2.addWidget(self.checkBox_FAM)
        self.checkBox_HEX = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_HEX.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBox_HEX.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox_HEX.setStyleSheet("background-color: transparent;\n"
"color: White")
        self.checkBox_HEX.setObjectName("checkBox_HEX")
        self.horizontalLayout_2.addWidget(self.checkBox_HEX)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.PCR_plate_container = QtWidgets.QWidget(self.centralwidget)
        self.PCR_plate_container.setMaximumSize(QtCore.QSize(16777215, 300))
        self.PCR_plate_container.setObjectName("PCR_plate_container")
        self.verticalLayout_2.addWidget(self.PCR_plate_container)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.action_e_aktar = QtWidgets.QAction(MainWindow)
        self.action_e_aktar.setObjectName("action_e_aktar")
        self.actionD_a_aktar = QtWidgets.QAction(MainWindow)
        self.actionD_a_aktar.setObjectName("actionD_a_aktar")
        self.actionTemizle = QtWidgets.QAction(MainWindow)
        self.actionTemizle.setObjectName("actionTemizle")
        self.actionFiltreleme = QtWidgets.QAction(MainWindow)
        self.actionFiltreleme.setObjectName("actionFiltreleme")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_esittir.setText(_translate("MainWindow", "="))
        self.label_belirsiz.setText(_translate("MainWindow", "Belirsiz"))
        self.label_tasiyici.setText(_translate("MainWindow", "Taşıyıcı"))
        self.label_saglikli_kontrol.setText(_translate("MainWindow", "Sağlıklı Kontrol"))
        self.checkBox_istatistik.setText(_translate("MainWindow", "İstatistik oranı ile nihai sonuçları belirle"))
        self.label_tasiyici_kontrol.setText(_translate("MainWindow", "Taşıyıcı Kontrol"))
        self.label_kucuk_esittir_2.setText(_translate("MainWindow", "≤"))
        self.label_ntc_kontrol.setText(_translate("MainWindow", "NTC"))
        self.pushButton_temizle.setText(_translate("MainWindow", "Temizle"))
        self.pushButton_analiz_et.setText(_translate("MainWindow", "Analiz Et"))
        self.pushButton_disaaktar.setText(_translate("MainWindow", "Dışa Aktar"))
        self.pushButton_iceaktar.setText(_translate("MainWindow", "İçe Aktar"))
        self.label_kucuk_esittir_1.setText(_translate("MainWindow", "≤"))
        self.label_standart_kuyu.setText(_translate("MainWindow", "Standart Kuyu"))
        self.label_drag_drop_area.setText(_translate("MainWindow", "RDML dosyanızı sürükleyip bırakınız"))
        self.table_widget_resulttable.setSortingEnabled(True)
        item = self.table_widget_resulttable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hasta No"))
        item = self.table_widget_resulttable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kuyu No"))
        item = self.table_widget_resulttable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Barkot No"))
        item = self.table_widget_resulttable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Hasta Adı"))
        item = self.table_widget_resulttable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Δ Ct"))
        item = self.table_widget_resulttable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Regresyon"))
        item = self.table_widget_resulttable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "İstatistik Oranı"))
        item = self.table_widget_resulttable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Standart Oranı"))
        item = self.table_widget_resulttable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Nihai Sonuç"))
        self.checkBox_FAM.setText(_translate("MainWindow", "FAM (SMN1)"))
        self.checkBox_HEX.setText(_translate("MainWindow", "HEX (ACTB)"))
        self.action_e_aktar.setText(_translate("MainWindow", "İçe aktar"))
        self.actionD_a_aktar.setText(_translate("MainWindow", "Dışa aktar"))
        self.actionTemizle.setText(_translate("MainWindow", "Temizle"))
        self.actionFiltreleme.setText(_translate("MainWindow", "Filtreleme"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
